from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional

app = FastAPI(title="Task Management API")

class Task(BaseModel):
    id: int
    title: str
    done: bool = False

class TaskCreate(BaseModel):
    title: str

class TaskUpdate(BaseModel):
    title: Optional[str] = None
    done: Optional[bool] = None

tasks: List[Task] = []
counter = 1

@app.post("/tasks", response_model=Task)
def create_task(task: TaskCreate):
    global counter
    if not task.title or task.title.strip() == "":
        raise HTTPException(status_code=400, detail="Title cannot be empty")
    new_task = Task(id=counter, title=task.title, done=False)
    tasks.append(new_task)
    counter += 1
    return new_task

@app.get("/tasks", response_model=List[Task])
def get_tasks():
    return tasks

@app.get("/tasks/{task_id}", response_model=Task)
def get_task(task_id: int):
    for task in tasks:
        if task.id == task_id:
            return task
    raise HTTPException(status_code=404, detail="Task not found")

@app.put("/tasks/{task_id}", response_model=Task)
def update_task(task_id: int, update: TaskUpdate):
    for task in tasks:
        if task.id == task_id:
            if update.title is not None:
                if update.title.strip() == "":
                    raise HTTPException(status_code=400, detail="Title cannot be empty")
                task.title = update.title
            if update.done is not None:
                task.done = update.done
            return task
    raise HTTPException(status_code=404, detail="Task not found")

@app.delete("/tasks/{task_id}")
def delete_task(task_id: int):
    for i, task in enumerate(tasks):
        if task.id == task_id:
            tasks.pop(i)
            return {"message": "Task deleted"}
    raise HTTPException(status_code=404, detail="Task not found")
## AI vs me

I compared my hand-written CRUD API against a version generated by AI from my own prompt.

What the AI did better: it used separate Pydantic models (Task, TaskCreate, TaskUpdate) for cleaner structure, and added a proper API title.

What I missed: I didn't specify status codes clearly enough in my prompt, so the AI's POST /tasks returned 200 instead of the correct 201 Created that my own version used.

What my prompt forgot to clarify: I didn't mention the / and /health endpoints, or ask for specific HTTP status codes for each action, so the AI had no way to know I wanted those.